fixed issue

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,8 +24,7 @@ jobs:
             echo -e "Host github.com\n\tHostName github.com\n\tIdentityFile /home/ubuntu/.ssh/temp_ssh/id_ed25519\n\tIdentitiesOnly yes" > /home/ubuntu/.ssh/config
             chmod 600 /home/ubuntu/.ssh/config
             echo "Pulling latest code:"
-            cd /home/ubuntu/xtwitter_bot  
-            git pull origin main || echo "Git pull failed"
+            GIT_SSH_COMMAND="ssh -i /home/ubuntu/.ssh/temp_ssh/id_ed25519 -o IdentitiesOnly=yes" git pull origin main || echo "Git pull failed"
             echo "Activating virtual environment:"
             source venv/bin/activate
             echo "Restarting bot:"
@@ -33,4 +32,3 @@ jobs:
             screen -dmS phil_bot venv/bin/python3 xtwitter_bot.py > bot.log 2>&1
             echo "Active screen sessions:"
             screen -ls
-
