testing again

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,17 +25,17 @@ jobs:
             echo "https://${{ secrets.FINEGRAINTOKEN }}@github.com" > ~/.git-credentials
             git config --global user.name "GitHub Actions Bot"
             git config --global user.email "actions@github.com"
-            git config --global --add safe.directory /home/ubuntu/xphilosphy_bot
+            git config --global --add safe.directory /home/ubuntu/xtwitter_bot
 
             echo "Pulling latest code using token:"
-            if [ ! -d "/home/ubuntu/xphilosphy_bot" ]; then
-              git clone https://${{ secrets.FINEGRAINTOKEN }}@github.com/donneypr/xphilosphy_bot.git /home/ubuntu/xphilosphy_bot
+            if [ ! -d "/home/ubuntu/xtwitter_bot" ]; then
+              git clone https://${{ secrets.FINEGRAINTOKEN }}@github.com/donneypr/xphilosphy_bot.git /home/ubuntu/xtwitter_bot
             else
-              cd /home/ubuntu/xphilosphy_bot && git pull origin main || echo "Git pull failed"
+              cd /home/ubuntu/xtwitter_bot && git pull origin main || echo "Git pull failed"
             fi
 
             echo "Activating virtual environment:"
-            cd /home/ubuntu/xphilosphy_bot
+            cd /home/ubuntu/xtwitter_bot
             source venv/bin/activate
 
             echo "Restarting bot:"
